### ISSUE TITLE
How to authenticate other mobile apps with Hypersign

### ISSUE THREAD

**Issue by vikramIde** [vikramIde/hs-android-app#11]
So for browser we will have qr based login but for mobile app, we will need to create OAuth flow between the Mobile app and our Hypersign AUthenticator.

**Task**

- [ ] Learn how to share data to other application
- [ ] How to create OAuth flow from one app to hypersign
- [ ] Create a sample code which can provide oAuth flow to other Mobile apps using Hypersign
